# Site settings
title:          Teran
description:    "Musings of a Hacker"
url:            "https://teranpeterson.com"

# Google Analytics
google_analytics: UA-125743006-1

# Author
author:
  name:         Teran Peterson
  url:          https://teranpeterson.com
  email:        mavr1k7@teranpeterson.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink:      /blog/:year-:month-:day/:title
paginate:       5
paginate_path:  "/blog/page:num/"

# Excludes
exclude: [ Gemfile, Gemfile.lock ]
